# Generated by Django 4.2.1 on 2023-06-17 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='picture',
            field=models.ImageField(upload_to='pic/'),
        ),
    ]
