# Generated by Django 4.2.1 on 2023-06-18 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_alter_pictures_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='name',
            field=models.CharField(default='pic', max_length=20),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='picture',
            field=models.ImageField(upload_to='pic'),
        ),
    ]
