# Generated by Django 4.2.1 on 2023-08-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_pictures_name_alter_pictures_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='GerenciadorTabelasHorarias',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('data_tabela', models.DateField(unique=True)),
            ],
            options={
                'db_table': 'gerenciador_tabelas_horarias',
                'managed': False,
            },
        ),
    ]
