# Generated by Django 4.2.1 on 2023-09-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_datelabel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalMax',
            fields=[
                ('codigo', models.BigIntegerField(primary_key=True, serialize=False)),
                ('dia', models.DateField()),
                ('maximo_umidade', models.FloatField()),
                ('maximo_pressao', models.FloatField()),
                ('maximo_temp_int', models.FloatField()),
                ('maximo_temp_ext', models.FloatField()),
            ],
            options={
                'db_table': 'maximas_totais',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TotalMeans',
            fields=[
                ('codigo', models.BigIntegerField(primary_key=True, serialize=False)),
                ('dia', models.DateField()),
                ('media_umidade', models.FloatField()),
                ('media_pressao', models.FloatField()),
                ('media_temp_int', models.FloatField()),
                ('media_temp_ext', models.FloatField()),
            ],
            options={
                'db_table': 'medias_totais',
                'managed': False,
            },
        ),
    ]
