# Generated by Django 4.2.1 on 2023-09-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0007_totalmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalMedian',
            fields=[
                ('codigo', models.BigIntegerField(primary_key=True, serialize=False)),
                ('dia', models.DateField()),
                ('mediana_umidade', models.FloatField()),
                ('mediana_pressao', models.FloatField()),
                ('mediana_temp_int', models.FloatField()),
                ('mediana_temp_ext', models.FloatField()),
            ],
            options={
                'db_table': 'medianas_totais',
                'managed': False,
            },
        ),
    ]
