# Generated by Django 4.2.1 on 2023-09-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0008_totalmedian'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalMode',
            fields=[
                ('codigo', models.BigIntegerField(primary_key=True, serialize=False)),
                ('dia', models.DateField()),
                ('moda_umidade', models.FloatField()),
                ('moda_pressao', models.FloatField()),
                ('moda_temp_int', models.FloatField()),
                ('moda_temp_ext', models.FloatField()),
            ],
            options={
                'db_table': 'modas_totais',
                'managed': False,
            },
        ),
    ]
