# Generated by Django 4.2.1 on 2023-09-02 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0010_genericviews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genericviews',
            options={'managed': False},
        ),
    ]
