# Generated by Django 4.2.1 on 2023-09-02 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0011_alter_genericviews_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='genericviews',
            table='genericViews',
        ),
    ]
