# Generated by Django 4.2.1 on 2023-09-02 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0012_alter_genericviews_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genericviews',
            options={},
        ),
    ]
