# Generated by Django 4.2.1 on 2023-09-02 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0013_alter_genericviews_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genericviews',
            options={'managed': False},
        ),
    ]
