# Generated by Django 4.2.1 on 2023-09-02 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0014_alter_genericviews_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='genericviews',
            table='genericviews',
        ),
    ]
